from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

_MPLCONFIGDIR = Path(os.environ.get("MPLCONFIGDIR", "/tmp/sota_counter_matplotlib"))
_MPLCONFIGDIR.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(_MPLCONFIGDIR))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from .constants import CONFERENCES, YEARS
from .core import pivot_counts, rounded_ratio_table


def write_tables(df: pd.DataFrame, out_dir: Path) -> dict[str, Path]:
    tables_dir = out_dir / "tables"
    tables_dir.mkdir(parents=True, exist_ok=True)

    accepted = pivot_counts(df, "accepted").astype(int)
    sota = pivot_counts(df, "sota").astype(int)
    ratios = rounded_ratio_table(df)

    paths = {
        "accepted_counts": tables_dir / "accepted_counts.csv",
        "sota_counts": tables_dir / "sota_counts.csv",
        "sota_ratios": tables_dir / "sota_ratios.csv",
        "appendix_a_tables": tables_dir / "appendix_a_tables.tex",
    }

    accepted.to_csv(paths["accepted_counts"])
    sota.to_csv(paths["sota_counts"])
    ratios.to_csv(paths["sota_ratios"], float_format="%.2f")

    with paths["appendix_a_tables"].open("w", encoding="utf-8") as handle:
        handle.write("% Generated by sota_counter.\n\n")
        handle.write("% Accepted-paper counts\n")
        handle.write(accepted.to_latex())
        handle.write("\n% SOTA-mention counts\n")
        handle.write(sota.to_latex())
        handle.write("\n% SOTA-mention ratios (percent)\n")
        handle.write(ratios.to_latex(float_format="%.2f"))

    return paths


def write_figure1(df: pd.DataFrame, out_dir: Path) -> dict[str, Path]:
    figure_dir = out_dir / "figure1"
    figure_dir.mkdir(parents=True, exist_ok=True)
    input_path = figure_dir / "figure1_input.csv"
    png_path = figure_dir / "trend.png"
    pdf_path = figure_dir / "trend.pdf"

    df.sort_values(["year", "conference"]).to_csv(input_path, index=False)

    plt.rcParams.update(
        {
            "font.size": 12,
            "axes.titlesize": 14,
            "axes.labelsize": 12,
            "xtick.labelsize": 11,
            "ytick.labelsize": 11,
            "legend.fontsize": 10,
            "figure.dpi": 150,
            "savefig.dpi": 300,
            "savefig.bbox": "tight",
        }
    )

    plot_df = df.copy()
    conferences = [conference.label for conference in CONFERENCES]
    years = list(YEARS)
    x = np.arange(len(years))
    width = 0.08
    n_confs = len(conferences)
    cmap = plt.get_cmap("tab10")
    colors = {conf: cmap(i) for i, conf in enumerate(conferences)}

    fig, ax = plt.subplots(figsize=(5.0, 2.2))
    for i, conf in enumerate(conferences):
        subset = plot_df[plot_df["conference"] == conf].sort_values("year")
        offset = (i - n_confs / 2 + 0.5) * width
        color = colors[conf]

        ax.bar(x + offset, subset["sota"].values, width, label=conf, color=color)
        ax.bar(
            x + offset,
            subset["non_sota"].values,
            width,
            bottom=subset["sota"].values,
            color=color,
            alpha=0.5,
        )

    ax.set_xlabel("Year")
    ax.set_ylabel("Number of Papers")
    ax.set_xticks(x)
    ax.set_xticklabels(years)
    ax.legend(bbox_to_anchor=(1.02, 0.45), loc="center left", frameon=False)
    ax.grid(True, alpha=0.3, axis="y")
    fig.tight_layout()
    fig.savefig(png_path)
    fig.savefig(pdf_path)
    plt.close(fig)

    return {"figure1_input": input_path, "trend_png": png_path, "trend_pdf": pdf_path}


def write_check(report: dict[str, Any], out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "check.json"
    with path.open("w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2, sort_keys=True)
        handle.write("\n")
    return path
